<h4>Hello {!! $mail_data['salon_name'] !!}</h4>
<h4>Hello {!! $mail_data['service_name'] !!}</h4>
<h4>Hello {!! $mail_data['staff_name'] !!}</h4>
<h4>Hello {!! $mail_data['date'] !!}</h4>
<h4>Hello {!! $mail_data['time'] !!}</h4>
<h4>Hello {!! $mail_data['name'] !!}</h4>
<h4>Hello {!! $mail_data['surname'] !!}</h4>
<h4>Hello {!! $mail_data['email'] !!}</h4>
<h4>Hello {!! $mail_data['phone'] !!}</h4>